name: uuid
version: 0.1.0
description: >
  RFC4122(v1,v4,v5) UUID Generator and Parser.
author: Yulian Kuncheff <yulian@kuncheff.com>
homepage: https://github.com/Daegalus/dart-uuid
dependencies:
  unittest: any
